services:
  - type: web
    name: n8n
    runtime: docker
    repo: https://github.com/nhutlm/n8n
    plan: free
    dockerCommand: ""
    dockerImage: docker.io/n8nio/n8n:latest
    envVars:
      - key: N8N_PROTOCOL
        value: https
      - key: WEBHOOK_URL
        value: https://n8n.onrender.com # Thay bằng domain thực tế sau khi triển khai
      - key: N8N_PORT
        value: 5678
      - key: N8N_BASIC_AUTH_ACTIVE
        value: true
      - key: N8N_BASIC_AUTH_USER
        value: your-username
      - key: N8N_BASIC_AUTH_PASSWORD
        value: your-strong-password
